version: '3.7'
services:
    workspace:
        build:
            context: ./.docker/workspace
            args:
                - PHP_VERSION=${PHP_VERSION}
        image: ${COMPOSE_PROJECT_NAME}_workspace:latest
        volumes:
            - ./:/var/htdocs
        tty: true

    php-cli:
        build:
            context: ./.docker/php-cli
            args:
                - PHP_VERSION=${PHP_VERSION}
                - XDEBUG_ENABLE=${XDEBUG_ENABLE}
                - XDEBUG_HOST=${XDEBUG_HOST}
                - XDEBUG_PORT=${XDEBUG_PORT}
                - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
        environment:
            - FUNC_TEST_ENV_FILE=.env.test.local
        image: ${COMPOSE_PROJECT_NAME}_cli:latest
        volumes:
            - ./:/var/htdocs

    php-fpm:
        build:
            context: ./.docker/php-fpm
            args:
                - PHP_VERSION=${PHP_VERSION}
                - XDEBUG_ENABLE=${XDEBUG_ENABLE}
                - XDEBUG_HOST=${XDEBUG_HOST}
                - XDEBUG_PORT=${XDEBUG_PORT}
                - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
                - OPCACHE_ENABLE=${OPCACHE_ENABLE}
        image: ${COMPOSE_PROJECT_NAME}_fpm:latest
        volumes:
            - ./:/var/htdocs

    nginx:
        build:
            context: ./.docker/nginx
        image: ${COMPOSE_PROJECT_NAME}_nginx:latest
        volumes:
            - ./public:/var/htdocs/public
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php-fpm
        ports:
            - "80:80"
            - "443:443"

    mariadb:
        image: 'mariadb:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - '3306:3306'
